- filename: DBLP.bib
  search_type: FEED
  source_name: Pacific-Asia Confereence on Information Systems
  source_url: ''
  search_parameters: 
    - endpoint: dblp
      params: SCOPE venue_key='conf/pacis' AND journal_abbreviated='pacis'
  comment: ''