- filename: DBLP.bib
  search_type: FEED
  source_name: Pacific-Asia Confereence on Information Systems
  source_url: ''
  search_parameters: 
    - endpoint: dblp
      params: 
        venue_key: conf/pacis
        journal_abbreviated: pacis
  comment: ''