- filename: DBLP.bib
  search_type: FEED
  source_name: Pacific-Asia Confereence on Information Systems
  source_url: ''
  search_parameters: 
    - endpoint: dblp
      params: SCOPE venue_key='conf/pacis' AND journal_abbreviated='pacis'
  comment: ''
- filename: pdfs.bib
  search_type: FEED
  source_name: PACIS
  source_url: pdfs
  search_parameters:
  - endpoint: pdfs_directory
    params: SCOPE path='pdfs' WITH conference='Pacific-Asia Confereence on Information Systems' AND sub_dir_pattern='year'
  comment: NA
